PATH := /usr/um/gcc-4.7.0/bin:$(PATH)
LD_LIBRARY_PATH := /usr/um/gcc-4.7.0/lib64
LD_RUN_PATH := /usr/um/gcc-4.7.0/lib64
MineEscape:
	g++ -Wall -Werror mineField.cpp proj2.cpp -O3 -std=c++11 -o MineEscape
clean:
	rm -f MineEscape *.o


